Token: ENC[AES256_GCM,data:LR5i/kJj4K3VOfSdkthCgUsMt9NTxDaI1Opos5n65pv4L9TfarZL4Lr+m2W2gE5Y61OkRINQvU7wHP/yEXwUomoxsjvgEQ/U,iv:kSHWZKNHONN7rOsNI8Uu3QmL9nYlSYfodiomkWAjCAY=,tag:7nGzOSEm7/IeCy3Rkr42mw==,type:str]
Target: ENC[AES256_GCM,data:8xQzBNKeUq1gT/253CyEOy7GAuvt2XS0pK8sMuSbNuNKCuM=,iv:YBMSvSyHF32Ri+0jd0yl2zTfQu22WFbJc+6XqiNLVTo=,tag:ORuEK8nnRHdE/VdgVA+Ykw==,type:str]
Prefix: ENC[AES256_GCM,data:xg==,iv:jw1yGBGVpx0QqzSRhH7Uxu6JeCfuLs+eniEQY3pmGyM=,tag:Uj58pb6LQMdM3w4OvIAjXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-06-05T08:04:50Z"
    mac: ENC[AES256_GCM,data:yMRMFTfs/z46eekXxlh6DJNSfvIqTMeaklC6kJ2ugNSVkfTZQ1rccwldUm3Aj6qMhFzg9TcbMRsjzIHQlQ43gLQ1S3H2EUbWUJYLLq7VGxRHOVeY9PDjmqGjkMvAFUEd3Pgulh9fXz+r71fhdZgtEyGi+U5mumOZX3rNme6I0Pk=,iv:Tphr5YYEQTF+8jCx4GgwNgcS57aLKrEDTu9U5bWfADU=,tag:9vqvkgF15mmhv1y5Sz2ewQ==,type:str]
    pgp:
        - created_at: "2024-05-18T14:52:01Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMA8zON7ktYatYAQv+NK9V5pQCTvl5l0IWy8tHZdogBTf6LHix40hvY/vsnW6g
            +PXE7Vhwe5LueabKaOY2iREMBo3w2qH9zPSnZNFAPABIT5446VjdDfA3blL3tybp
            ByvFZm9WxYjiPtqI06OXNaZYa8KViL54h032iP4Vu1ZvEbv35K9rdZ3a9T80t4si
            d0W9wCLsAz7LnL/TqbgNCQN/nbeRJ8LD0AYogPM+MlpxEFa8mfCKq6euKawgGXLN
            4Q84nGnwMqWoILUAB3EvOjsKBM2AGHVoCuAGDnantIioIKPLT0BWPpwv9G5DNx/q
            0AImySqpYyzFpv11qJJt9Nw3YHEuQSKuCfKZwSOwYAOd3WqSZpCVcVzXxrRDZofD
            8qbCCTxakicA0cKbU5SNgMm7w4+x3O4c8oIO1gFBvb6sKVLh4lhwue13r/Vl9o7L
            fKX96jLw6h/w0dRwKx+I49lDnJaMKEY5XCA9FITiEM5zKWc5t3NnB++JqGq9iWFw
            90K5LAJWUZFHTF/1roeP0lwByHIljhVMCiyNVgLOVoR8QIGUFMJKRFpKd/6gCuUZ
            12ga+1F95/sTI3DtYbWmxrAr9RmkmrunL+NNRKe88Dvhk714P9rGwTfT74X4nWBY
            YE1xKI54Vb33G08NCA==
            =xqZU
            -----END PGP MESSAGE-----
          fp: 934A63EA24CF150D06E9F710E76E05F2100AA7EA
    unencrypted_suffix: _unencrypted
    version: 3.8.1
