name: Go Builder
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  linux-build:
    name: Go Build
    runs-on: ubuntu-latest
    container:
      image: golang:1.22-alpine
    steps:
      - run: |
          apk add git make bash sops gnupg
          git config --global user.email "bogus@example.com"
          git config --global user.name "Someone"
          git config --global --add safe.directory /__w/gobot/gobot
      - uses: nhedger/setup-sops@v2
        id: secrets
        with:
          version: 3.8.1
      - name: Create key.gpg
        run: echo -e "$SOPS_KEY" | base64 -d | sed 's/\\n/\'$'\n''/g' > key.gpg
        env:
          SOPS_KEY: ${{ secrets.SOPS_KEY }}
      - name: Import key.gpg
        run: gpg --import key.gpg
      - uses: actions/checkout@v4
      - name: Decrypt config.enc.yaml
        run: sops -d config.enc.yaml > config.yaml
      - run: make build
        if: ${{ hashFiles('.skip_ci') == '' }}
      - name: Save binary
        if: ${{ hashFiles('.skip_ci') == '' }}
        uses: actions/upload-artifact@v4
        with:
          name: gobot
          path: bin/gobot
      - run: make test
        if: ${{ hashFiles('.skip_ci') == '' }}
      - name: Upload Coverage Output
        if: ${{ hashFiles('.skip_ci') == '' }}
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: c.out
      - name: Update coverage report
        if: ${{ hashFiles('.skip_ci') == '' }}
        uses: actions/checkout@v4
      - uses: fgrosse/go-coverage-report@v1.0.1
        if: ${{ hashFiles('.skip_ci') == '' }}
        with:
          coverage-artifact-name: code-coverage
          coverage-file-name: c.out
        continue-on-error: true
