name: Go Builder
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  linux-build:
    name: Go Build
    runs-on: ubuntu-latest
    container:
      image: golang:1.22-alpine
    steps:
      - run: |
          echo "Event name is: " ${{ github.event_name }}
          echo "Event type is: " ${{ github.event.action }}
      - run: |
          apk add git make bash
          git config --global user.email "bogus@example.com"
          git config --global user.name "Someone"
          git config --global --add safe.directory /__w/gobot/gobot
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: make build
      - name: Save binary
        uses: actions/upload-artifact@v4
        with:
          name: gobot
          path: bin/gobot
      - run: make test
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          HEARTBEAT_URL: "https://google.com"
      - name: Upload Coverage Output
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: c.out

  code-coverage:
      name: Update coverage report
      if: github.event_name == 'push'
      runs-on: ubuntu-latest
      needs: linux-build
      steps:
        - uses: actions/fgrosse/go-coverage-report@v1.0.1
          with:
            coverage-artifact-name: code-coverage
            coverage-file-name: c.out
          continue-on-error: true
