name: Go Builder
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  linux-build:
    name: Go Build
    runs-on: ubuntu-latest
    container:
      image: golang:1.22-alpine
    steps:
      - uses: metro-digital/sops-decrypt@v0.x
        id: secrets
        with:
          version: 3.8.1
          file: config.yaml
          gpg_key: ${{ secrets.SOPS_KEY }}
          output_type: json
      - run: |
          apk add git make bash
          git config --global user.email "bogus@example.com"
          git config --global user.name "Someone"
          git config --global --add safe.directory /__w/gobot/gobot
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          cat << EOF > ./config.yaml
          Token: ${{ fromJson(steps.secrets.outputs.data).Token }}
          Target: ${{  fromJson(steps.secrets.outputs.data).Target }}
          Prefix: ${{  fromJson(steps.secrets.outputs.data).Prefix }}
          EOF
      - run: make build
      - name: Save binary
        uses: actions/upload-artifact@v4
        with:
          name: gobot
          path: bin/gobot
      - run: make test
      - name: Upload Coverage Output
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: c.out

  code-coverage:
      name: Update coverage report
      runs-on: ubuntu-latest
      needs: linux-build
      steps:
        - uses: actions/checkout@v4
        - uses: fgrosse/go-coverage-report@v1.0.1
          with:
            coverage-artifact-name: code-coverage
            coverage-file-name: c.out
          continue-on-error: true
