name: Trivy Image Scanner
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build:
    name: Trivy Image Scan
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
      DOCKER_CLI_EXPERIMENTAL: enabled
    steps:
    - uses: actions/checkout@v4
    - name: Quick build (linux/alpine only)
      if: ${{ hashFiles('.skip_ci') }} == ''
      run: |
        docker build --target gobot-alpine -t gobot .
    - name: Run Trivy vulnerability scanner (table output)
      if: ${{ hashFiles('.skip_ci') }} == ''
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: gobot
        format: table
        exit-code: 1
        ignore-unfixed: true
        vuln-type: os,library
        severity: CRITICAL,HIGH
    - name: Run Trivy vulnerability scanner
      if: ${{ hashFiles('.skip_ci') }} == ''
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: gobot
        format: sarif
        output: trivy-results.sarif
        # exit-code: 1
        ignore-unfixed: true
        vuln-type: os,library
        # The SARIF format ignores severity and uploads all vulnerabilities for
        # later triage. The table-format step above is used to fail the build if
        # there are any critical or high vulnerabilities.
        # See https://github.com/aquasecurity/trivy-action/issues/95
        # severity: 'CRITICAL,HIGH'
        trivyignores: .trivyignore
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'
      if: (always() && github.repository == 'awayfromserver/gobot') && hashFiles('.skip_ci') == ''
