name: Labeler
on:
  - pull_request
  # pull_request_target:
  #   types: [ opened ]
  #   branches: [ main ]

jobs:
  label:
    name: Label
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
