name: Labeler
on:
  pull_request_target:
    types: [ opened ]
    branches: [ main ]

jobs:
  label:
    name: Label
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4 # Uploads repository content to the runner
      with:
        repository: "AwayFromServer/gobot"
    - uses: actions/labeler@v5
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
